rules:
  # === Security Rules ===

  - id: no-hardcoded-secrets
    patterns:
      - pattern-regex: '(?i)(password|secret|api[_-]?key|token|credentials)\s*[:=]\s*["\x27][^\"\x27]{8,}["\x27]'
    message: "Hardcoded secret detected. Use environment variables instead."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-798: Use of Hard-coded Credentials"

  - id: no-eval
    pattern: eval(...)
    message: "Avoid using eval() as it can lead to code injection vulnerabilities."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-95: Eval Injection"

  - id: no-dangerouslysetinnerhtml
    pattern: dangerouslySetInnerHTML={...}
    message: "Avoid dangerouslySetInnerHTML as it can lead to XSS vulnerabilities."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-79: Cross-site Scripting (XSS)"

  # === React/Next.js Best Practices ===

  - id: no-console-in-production
    pattern: console.log(...)
    message: "Avoid console.log in production code."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: best-practices

  - id: react-missing-key-prop
    pattern: |
      $ARRAY.map(($ITEM) => <$COMPONENT ... />)
    pattern-not: |
      $ARRAY.map(($ITEM) => <$COMPONENT key={...} ... />)
    message: "Missing 'key' prop in list rendering."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: react

  - id: useeffect-missing-deps
    pattern: |
      useEffect(() => { ... $VAR ... }, [])
    message: "useEffect may be missing dependencies in the dependency array."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: react

  # === Code Quality ===

  - id: no-explicit-any-parameter
    pattern: |
      function $FUNC(..., $PARAM: any, ...): $RET { ... }
    message: "Avoid using 'any' type for function parameters. Use specific types or 'unknown'."
    languages: [typescript]
    severity: WARNING
    metadata:
      category: code-quality

  - id: catch-error-without-handling
    pattern: |
      catch ($ERR) {
      }
    message: "Empty catch block. Error should be logged or re-thrown."
    languages: [typescript]
    severity: ERROR
    metadata:
      category: error-handling

  # === Next.js Specific ===

  - id: no-img-element
    pattern: <img ... />
    message: "Use next/image instead of <img> for better performance."
    languages: [typescript, javascript]
    severity: INFO
    metadata:
      category: nextjs
