rules:
  # === Security Rules ===

  - id: no-hardcoded-secrets
    pattern-regex: '(?i)(password|secret|api[_-]?key|token|credentials)\s*[:=]\s*["\x27][^\"\x27]{8,}["\x27]'
    message: "Hardcoded secret detected. Use environment variables instead."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-798: Use of Hard-coded Credentials"

  - id: no-eval
    pattern: eval(...)
    message: "Avoid using eval() as it can lead to code injection vulnerabilities."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      cwe: "CWE-95: Eval Injection"

  - id: no-dangerouslysetinnerhtml
    pattern: dangerouslySetInnerHTML={...}
    message: "Avoid dangerouslySetInnerHTML as it can lead to XSS vulnerabilities."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-79: Cross-site Scripting (XSS)"

  # === React/Next.js Best Practices ===

  - id: no-console-log
    pattern: console.log(...)
    message: "Avoid console.log in production code."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: best-practices

  - id: empty-catch-block
    pattern: |
      catch ($ERR) {
      }
    message: "Empty catch block. Error should be logged or re-thrown."
    languages: [typescript]
    severity: ERROR
    metadata:
      category: error-handling

  # === Code Quality ===

  - id: no-any-type-annotation
    pattern: "$VAR: any"
    message: "Avoid using 'any' type. Use specific types or 'unknown'."
    languages: [typescript]
    severity: WARNING
    metadata:
      category: code-quality

  # === Next.js Specific ===

  - id: prefer-next-image
    pattern: <img $...ATTRS />
    message: "Consider using next/image instead of <img> for better performance."
    languages: [typescript, javascript]
    severity: INFO
    metadata:
      category: nextjs
